# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = [
  "pre-commit",
  "commit-msg"
  ]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
hooks = [
  {
    id = "conventional-pre-commit",
    stages = ["commit-msg"],
    args = ["--verbose"]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.20"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "ty",
    name = "ty check",
    entry = "uv run ty check",
    language = "system",
    types = ["python"],
    pass_filenames = true
  }
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "detect-private-key" },
  { id = "check-added-large-files" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-json" },
]
